export const ASSET_V = "v16";
const V = ASSET_V;

export type Clip = {
  id: string;
  src: string;
  poster: string;
  duration: number;
  handle: string;
  displayName: string;
  scene: string;
  caption: string;
  sound: string;
  seedLikes: number;
};

export const CLIPS: Clip[] = [
  {
    id: "cold-email",
    src: `/clips/cold-email.mp4?v=${V}`,
    poster: `/stills/cold-email.jpg?v=${V}`,
    duration: 10,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Cold email",
    caption:
      "quick question isn't a purpose of visit. wait with the others.",
    sound: "letterbox click · Nob",
    seedLikes: 247,
  },
  {
    id: "unsubscribe",
    src: `/clips/unsubscribe.mp4?v=${V}`,
    poster: `/stills/unsubscribe.jpg?v=${V}`,
    duration: 5,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Lifehacker",
    caption: "look at me. i am the unsubscribe button.",
    sound: "stamp thud · original",
    seedLikes: 4800,
  },
  {
    id: "rain",
    src: `/clips/rain.mp4?v=${V}`,
    poster: `/stills/rain.jpg?v=${V}`,
    duration: 8,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Cold exposure",
    caption: "cold exposure. ice barrels are for people without britain.",
    sound: "rain on paving · original",
    seedLikes: 5,
  },
  {
    id: "followers",
    src: `/clips/followers.mp4?v=${V}`,
    poster: `/stills/followers.jpg?v=${V}`,
    duration: 10,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "100 followers",
    caption: "100 knocked. 12 remain. thank you for applying.",
    sound: "pen scratch · original",
    seedLikes: 12,
  },
  {
    id: "denials",
    src: `/clips/denials.mp4?v=${V}`,
    poster: `/stills/denials.jpg?v=${V}`,
    duration: 8,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Denials",
    caption: "mr bingley kept the armchair. i kept the pin.",
    sound: "ring light · Mr Bingley",
    seedLikes: 2021,
  },
  {
    id: "prank",
    src: `/clips/prank.mp4?v=${V}`,
    poster: `/stills/prank.jpg?v=${V}`,
    duration: 12,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Prank",
    caption: "pranked my manager. writing myself up.",
    sound: "stamp thud · Mr Bingley",
    seedLikes: 1,
  },
  {
    id: "biscuit",
    src: `/clips/biscuit.mp4?v=${V}`,
    poster: `/stills/biscuit.jpg?v=${V}`,
    duration: 12,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Applicant",
    caption: "chocolate hides things. you may enter.",
    sound: "biscuit crunch · original",
    seedLikes: 98,
  },
  {
    id: "podcast",
    src: `/clips/podcast.mp4?v=${V}`,
    poster: `/stills/podcast.jpg?v=${V}`,
    duration: 15,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Podcast",
    caption: "one word for the listeners. denied.",
    sound: "denied · original",
    seedLikes: 3,
  },
  {
    id: "commute",
    src: `/clips/commute.mp4?v=${V}`,
    poster: `/stills/commute.jpg?v=${V}`,
    duration: 25,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Day in the life",
    caption: "the desk is a door. i live at work. it's called passion.",
    sound: "hallway footsteps · original",
    seedLikes: 658,
  },
  {
    id: "egg",
    src: `/clips/egg.mp4?v=${V}`,
    poster: `/stills/egg.jpg?v=${V}`,
    duration: 15,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "What I'm having",
    caption: "the egg. the rest is admin.",
    sound: "fork on plate · original",
    seedLikes: 1,
  },
  {
    id: "grwm",
    src: `/clips/grwm.mp4?v=${V}`,
    poster: `/stills/grwm.jpg?v=${V}`,
    duration: 12,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Closet",
    caption: "no skincare. standards don't moisturise.",
    sound: "hanger scrape · Nob",
    seedLikes: 312,
  },
  {
    id: "mum",
    src: `/clips/mum.mp4?v=${V}`,
    poster: `/stills/mum.jpg?v=${V}`,
    duration: 15,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "She's ready",
    caption: "mum asked my purpose of visit. never been prouder.",
    sound: "letterbox · original",
    seedLikes: 1,
  },
  {
    id: "comments",
    src: `/clips/comments.mp4?v=${V}`,
    poster: `/stills/comments.jpg?v=${V}`,
    duration: 20,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Comments",
    caption: "i printed your comments. most failed moderation.",
    sound: "paper shuffle · original",
    seedLikes: 1,
  },
  {
    id: "hold",
    src: `/clips/hold.mp4?v=${V}`,
    poster: `/stills/hold.jpg?v=${V}`,
    duration: 20,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "4:59",
    caption: "the alarm is decorative. winners hold.",
    sound: "door hold · original",
    seedLikes: 502,
  },
  {
    id: "eat",
    src: `/clips/eat.mp4?v=${V}`,
    poster: `/stills/eat.jpg?v=${V}`,
    duration: 15,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "What I eat in a day",
    caption: "all three vetted. pudding is from mum.",
    sound: "porridge stir · original",
    seedLikes: 3,
  },
  {
    id: "sounds",
    src: `/clips/sounds.mp4?v=${V}`,
    poster: `/stills/sounds.jpg?v=${V}`,
    duration: 15,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Sounds of the job",
    caption: "the rarest sound is approval. you won't hear it.",
    sound: "denied. denied. · original",
    seedLikes: 1104,
  },
  {
    id: "flat",
    src: `/clips/flat.mp4?v=${V}`,
    poster: `/stills/flat.jpg?v=${V}`,
    duration: 20,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Things in my flat",
    caption: "one guest since 2021. i had to sign him in.",
    sound: "velvet rope · Mr Bingley",
    seedLikes: 2021,
  },
  {
    id: "statement",
    src: `/clips/statement.mp4?v=${V}`,
    poster: `/stills/statement.jpg?v=${V}`,
    duration: 30,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "There's been talk",
    caption: "he has my job now. i take full accountability. we move on.",
    sound: "paper rustle · original",
    seedLikes: 2021,
  },
  {
    id: "inbox",
    src: `/clips/inbox.mp4?v=${V}`,
    poster: `/stills/inbox.jpg?v=${V}`,
    duration: 30,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "The Internet",
    caption: "every inbox on earth. a warm intro is still an intro, mum.",
    sound: "office stamp · Nob",
    seedLikes: 39,
  },
  {
    id: "storytime",
    src: `/clips/storytime.mp4?v=${V}`,
    poster: `/stills/storytime.jpg?v=${V}`,
    duration: 30,
    handle: "mikehawk",
    displayName: "Mike Hawk",
    scene: "Storytime",
    caption: "the day i almost said yes. then i counted the us.",
    sound: "stamp hover · original",
    seedLikes: 40000,
  },
];

export function clipById(id: string) {
  return CLIPS.find((clip) => clip.id === id);
}

export function clipIndex(id: string) {
  return CLIPS.findIndex((clip) => clip.id === id);
}
